# ------------------------------------------------------------------------
#
# Logging Configuration
#
# $Id: Log4j.properties
#
# ------------------------------------------------------------------------
#

#
# If we don't know the logging facility, put it into the
# turbine.log
#
log4j.rootLogger = DEBUG, turbine

#
# Turbine goes into Turbine Log
#
log4j.category.org.apache.turbine = DEBUG, turbine
log4j.additivity.org.apache.turbine = false

#DWR 
log4j.logger.uk.ltd.getahead.dwr = DEBUG, dwr
log4j.additivity.uk.ltd.getahead.dwr = false

#
# Torque has its own log file
#
log4j.category.org.apache.torque = DEBUG, torque
log4j.additivity.org.apache.torque = false

#
# Velocity Logfile
#
log4j.category.velocity = DEBUG, velocity
log4j.additivity.velocity = false

#
# Scheduler Category
#
log4j.category.scheduler = DEBUG, scheduler
log4j.additivity.scheduler = false

#
# Hibernate Category
#
log4j.category.net.sf.hibernate = DEBUG, turbine
log4j.additivity.net.sf.hibernate = false


########################################################################
#
# Logfile definitions
#
########################################################################

#
# turbine.log
#
log4j.appender.turbine = org.apache.log4j.FileAppender
log4j.appender.turbine.file = ${applicationRoot}/logs/turbine.log
log4j.appender.turbine.layout = org.apache.log4j.PatternLayout
log4j.appender.turbine.layout.conversionPattern = %d [%t] %-5p %c - %m%n
log4j.appender.turbine.append = false

#
# dwr.log
#
log4j.appender.dwr = org.apache.log4j.FileAppender
log4j.appender.dwr.file = ${applicationRoot}/logs/dwr.log
log4j.appender.dwr.layout = org.apache.log4j.PatternLayout
log4j.appender.dwr.layout.conversionPattern = %d [%t] %-5p %c - %m%n
log4j.appender.dwr.append = false

#
# torque.log
#
log4j.appender.torque = org.apache.log4j.FileAppender
log4j.appender.torque.file = ${applicationRoot}/logs/torque.log
log4j.appender.torque.layout = org.apache.log4j.PatternLayout
log4j.appender.torque.layout.conversionPattern = %d [%t] %-5p %c - %m%n
log4j.appender.torque.append = false

#
# Scheduler Output
#
log4j.appender.scheduler = org.apache.log4j.FileAppender
log4j.appender.scheduler.file = ${applicationRoot}/logs/scheduler.log
log4j.appender.scheduler.layout = org.apache.log4j.PatternLayout
log4j.appender.scheduler.layout.conversionPattern = %d [%t] %-5p %c - %m%n
log4j.appender.scheduler.append = false

#
# Velocity gets configured to write its output onto the velocity
# category.
#
log4j.appender.velocity = org.apache.log4j.FileAppender
log4j.appender.velocity.file = ${applicationRoot}/logs/velocity.log
log4j.appender.velocity.layout = org.apache.log4j.PatternLayout
log4j.appender.velocity.layout.conversionPattern = %d [%t] %-5p %c - %m%n
log4j.appender.velocity.append = false


