
INSERT INTO TURBINE_GROUP (GROUP_ID,GROUP_NAME)
    VALUES (1,'global');
INSERT INTO TURBINE_PERMISSION (PERMISSION_ID,PERMISSION_NAME)
    VALUES (1,'admin_users');
INSERT INTO TURBINE_PERMISSION (PERMISSION_ID,PERMISSION_NAME)
    VALUES (2,'admin_groups');
INSERT INTO TURBINE_PERMISSION (PERMISSION_ID,PERMISSION_NAME)
    VALUES (3,'admin_roles');
INSERT INTO TURBINE_PERMISSION (PERMISSION_ID,PERMISSION_NAME)
    VALUES (4,'admin_permissions');
INSERT INTO TURBINE_ROLE (ROLE_ID,ROLE_NAME)
    VALUES (1,'root');
INSERT INTO TURBINE_ROLE_PERMISSION (ROLE_ID,PERMISSION_ID)
    VALUES (1,1);
INSERT INTO TURBINE_ROLE_PERMISSION (ROLE_ID,PERMISSION_ID)
    VALUES (1,2);
INSERT INTO TURBINE_ROLE_PERMISSION (ROLE_ID,PERMISSION_ID)
    VALUES (1,3);
INSERT INTO TURBINE_ROLE_PERMISSION (ROLE_ID,PERMISSION_ID)
    VALUES (1,4);
INSERT INTO TURBINE_USER (USER_ID,LOGIN_NAME,PASSWORD_VALUE,FIRST_NAME,LAST_NAME)
    VALUES (1,'root','root','root','root');
INSERT INTO TURBINE_USER_GROUP_ROLE (USER_ID,GROUP_ID,ROLE_ID)
    VALUES (1,1,1);
    
INSERT INTO ID_TABLE (ID_TABLE_ID,TABLE_NAME,NEXT_ID,QUANTITY)
    VALUES (2,'TURBINE_USER',2,1);    
INSERT INTO ID_TABLE (ID_TABLE_ID,TABLE_NAME,NEXT_ID,QUANTITY)
    VALUES (3,'TURBINE_ROLE',2,1);        
INSERT INTO ID_TABLE (ID_TABLE_ID,TABLE_NAME,NEXT_ID,QUANTITY)
    VALUES (4,'TURBINE_GROUP',2,1);    
INSERT INTO ID_TABLE (ID_TABLE_ID,TABLE_NAME,NEXT_ID,QUANTITY)
    VALUES (1,'TURBINE_PERMISSION',2,1);        
